apiVersion: apps/v1
kind: Deployment
metadata:
  name: krr-app
  labels:
    app: krr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krr-app
  template:
    metadata:
      labels:
        app: krr-app
    spec:
      containers:
      - name: krr-app
        image: krr-app-image
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: krr-app-service
spec:
  selector:
    app: krr-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000